package com.digiwin.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-05-17T16:57:55.692+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://webservice.digiwin.com/", name = "EOSWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface EOSWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "modifyUser", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.ModifyUser")
    @WebMethod(action = "urn:ModifyUser")
    @ResponseWrapper(localName = "modifyUserResponse", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.ModifyUserResponse")
    public java.lang.String modifyUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateUserLogin", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.ValidateUserLogin")
    @WebMethod(action = "urn:ValidateUserLogin")
    @ResponseWrapper(localName = "validateUserLoginResponse", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.ValidateUserLoginResponse")
    public boolean validateUserLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.RegisterUser")
    @WebMethod(action = "urn:RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.RegisterUserResponse")
    public java.lang.String registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deactivateUser", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.DeactivateUser")
    @WebMethod(action = "urn:DeactivateUser")
    @ResponseWrapper(localName = "deactivateUserResponse", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.DeactivateUserResponse")
    public java.lang.String deactivateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "activateUser", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.ActivateUser")
    @WebMethod(action = "urn:ActivateUser")
    @ResponseWrapper(localName = "activateUserResponse", targetNamespace = "http://webservice.digiwin.com/", className = "com.digiwin.webservice.ActivateUserResponse")
    public java.lang.String activateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
