package org.yifeigateway.dcms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-07T15:56:27.263+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "YiFeiGateWayService", 
                  wsdlLocation = "http://192.168.1.88/yifeigateway/YiFeiGateway.asmx?WSDL",
                  targetNamespace = "http://dcms.YiFeiGateWay.org/") 
public class YiFeiGateWayService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dcms.YiFeiGateWay.org/", "YiFeiGateWayService");
    public final static QName YiFeiGateWayServiceSoap = new QName("http://dcms.YiFeiGateWay.org/", "YiFeiGateWayServiceSoap");
    public final static QName YiFeiGateWayServiceSoap12 = new QName("http://dcms.YiFeiGateWay.org/", "YiFeiGateWayServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.88/yifeigateway/YiFeiGateway.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(YiFeiGateWayService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.88/yifeigateway/YiFeiGateway.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public YiFeiGateWayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YiFeiGateWayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YiFeiGateWayService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns YiFeiGateWayServiceSoap
     */
    @WebEndpoint(name = "YiFeiGateWayServiceSoap")
    public YiFeiGateWayServiceSoap getYiFeiGateWayServiceSoap() {
        return super.getPort(YiFeiGateWayServiceSoap, YiFeiGateWayServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YiFeiGateWayServiceSoap
     */
    @WebEndpoint(name = "YiFeiGateWayServiceSoap")
    public YiFeiGateWayServiceSoap getYiFeiGateWayServiceSoap(WebServiceFeature... features) {
        return super.getPort(YiFeiGateWayServiceSoap, YiFeiGateWayServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns YiFeiGateWayServiceSoap
     */
    @WebEndpoint(name = "YiFeiGateWayServiceSoap12")
    public YiFeiGateWayServiceSoap getYiFeiGateWayServiceSoap12() {
        return super.getPort(YiFeiGateWayServiceSoap12, YiFeiGateWayServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YiFeiGateWayServiceSoap
     */
    @WebEndpoint(name = "YiFeiGateWayServiceSoap12")
    public YiFeiGateWayServiceSoap getYiFeiGateWayServiceSoap12(WebServiceFeature... features) {
        return super.getPort(YiFeiGateWayServiceSoap12, YiFeiGateWayServiceSoap.class, features);
    }

}
