package org.yifeigateway.dcms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-07T15:56:27.138+08:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://dcms.YiFeiGateWay.org/", name = "YiFeiGateWayServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface YiFeiGateWayServiceSoap {

    @WebResult(name = "TestConnectResult", targetNamespace = "http://dcms.YiFeiGateWay.org/")
    @RequestWrapper(localName = "TestConnect", targetNamespace = "http://dcms.YiFeiGateWay.org/", className = "org.yifeigateway.dcms.TestConnect")
    @WebMethod(operationName = "TestConnect", action = "http://dcms.YiFeiGateWay.org/TestConnect")
    @ResponseWrapper(localName = "TestConnectResponse", targetNamespace = "http://dcms.YiFeiGateWay.org/", className = "org.yifeigateway.dcms.TestConnectResponse")
    public java.lang.String testConnect(
        @WebParam(name = "inputStr", targetNamespace = "http://dcms.YiFeiGateWay.org/")
        java.lang.String inputStr
    );

    @WebResult(name = "YiFeiGatewayResult", targetNamespace = "http://dcms.YiFeiGateWay.org/")
    @RequestWrapper(localName = "YiFeiGateway", targetNamespace = "http://dcms.YiFeiGateWay.org/", className = "org.yifeigateway.dcms.YiFeiGateway")
    @WebMethod(operationName = "YiFeiGateway", action = "http://dcms.YiFeiGateWay.org/YiFeiGateway")
    @ResponseWrapper(localName = "YiFeiGatewayResponse", targetNamespace = "http://dcms.YiFeiGateWay.org/", className = "org.yifeigateway.dcms.YiFeiGatewayResponse")
    public java.lang.String yiFeiGateway(
        @WebParam(name = "inputXml", targetNamespace = "http://dcms.YiFeiGateWay.org/")
        java.lang.String inputXml
    );
}
